### ISSUE TITLE
1.20.1 version

### ISSUE THREAD

**Issue by Letus252** [BluCobalt/realmsfix#4]
Hey, could you port this mod to minecraft 1.20.1? The latest version of your mod is for 1.20.4 but most mods I'm using are still on 1.20.1/1.20.2. (Also thanks for making this mod, Realms button is really usless).

**Comment by BluCobalt** [comment]
![image](https://github.com/BluCobalt/realmsfix/assets/37788256/a290248b-038f-40d1-b559-0d2754ceb583)

**Comment by BluCobalt** [comment]
Should work now! https://modrinth.com/mod/realms-button-remover/version/2.0.2
