### ISSUE TITLE
Crash on 1.19.4

### ISSUE THREAD

**Issue by Junnaturefox** [BluCobalt/realmsfix#5]
logs
[https://mclo.gs/Zng5dgr](https://mclo.gs/Zng5dgr)

my mods list
![QQ截图20240218224557](https://github.com/BluCobalt/realmsfix/assets/104568909/0f88856b-9ad2-4924-9f4f-0338d635ac5f)

**Comment by BluCobalt** [comment]
[realmsfix-2.0.2.jar.zip](https://github.com/BluCobalt/realmsfix/files/14365481/realmsfix-2.0.2.jar.zip)
Does this work?
