### ISSUE TITLE
1.21 crash

### ISSUE THREAD

**Issue by m-sarabi** [BluCobalt/realmsfix#7]
Game crash on launch.

Mod version: 2.0.4

### List of other mods
```
BadOptimizations-2.1.4-1.21.jar
bettercommandblockui-0.5.2-1.21.jar
bettermounthud-1.2.4.jar
clientcommands-2.9.jar
enhancedblockentities-0.10.1+1.21.jar
fabric-api-0.100.7+1.21.jar
fabric-carpet-1.21-1.4.147+v240613.jar
fadeless-1.0.1.jar
ferritecore-7.0.0-fabric.jar
ImmediatelyFast-Fabric-1.2.18+1.21.jar
itemscroller-fabric-1.21-0.23.999-sakura.7.jar
journeymap-fabric-1.21-6.0.0-beta.18.jar
krypton-0.2.8.jar
litematica-fabric-1.21-0.18.999-sakura.29.jar
lithium-fabric-mc1.21-0.12.7.jar
malilib-fabric-1.21.0-0.20.2.jar
minihud-fabric-1.21-0.31.999-sakura.14.jar
modmenu-11.0.1.jar
NBTac-FABRIC-1.21-1.3.3.jar
noglow-1.1.1.jar
Notebook-4.0.2.jar
reeses_sodium_options-1.7.3+mc1.21.jar
sodium-extra-0.5.7+mc1.21.jar
sodium-fabric-0.5.11+mc1.21.jar
tweakeroo-fabric-1.21-0.20.999-sakura.21.jar
```

### Crash report
[crash-2024-07-29_02.56.04-client.txt](https://github.com/user-attachments/files/16405569/crash-2024-07-29_02.56.04-client.txt)

**Comment by BluCobalt** [comment]
[realmsfix-2.0.5-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/16451382/realmsfix-2.0.5-SNAPSHOT.jar.zip) does this work? (take off the .zip part, github doesn't allow you to upload .jar files directly)

**Comment by BluCobalt** [comment]
I can't reproduce that error, though. In the above file I just bumped the `compatibilityLevel` of the mixins for 1.21 to see if that would do anything. With Linux, Java 21, and Minecraft 1.21, and with and without other mods, it (2.0.4) works fine for me.

**Comment by m-sarabi** [comment]
Unfortunately, It did not resolve it:

```
The game crashed whilst rendering overlay
Error: java.lang.ClassCastException: class net.minecraft.class_8828$1 cannot be cast to class
dev.blucobalt.realmsfix.mixin.TranslatableTextAccessor1_21 (net.minecraft.class_8828$1 and
dev.blucobalt.realmsfix.mixin.TranslatableTextAccessor1_21 are in unnamed module of loader
net.fabricmc.loader.impl.launch.knot.KnotClassLoader @69b794e2)
```

Without other mods, it worked well, but adding other mods made the game crash. So I experimented with different combinations.

In the end, it looks like a compatibility issue with the [Vanilla Notebook](https://modrinth.com/mod/notebook/version/4.0.3) mod (that was the last mod I tested 😅)
I will create an issue on their repo as well.

**Comment by JunePrimavera** [comment]
From what I can tell this is more of an issue with this mod than my mod unless I am missing something here
I am very sleep deprived (+ a bit rusty on minecraft modding and java in general) so i might be misinterpreting your code but it seems like you are assuming each `Drawable` has `TranslatableText` which may not always be the case.

**Comment by BluCobalt** [comment]
Thank you :)
