### ISSUE TITLE
Since Last Update, Realmsfix Crash on Startup from Client (Fabric 1.21.1 on 0.16.9)

### ISSUE THREAD

**Issue by suerion** [BluCobalt/realmsfix#9]
https://mclo.gs/a9DKqBg

Had updated Realmsfix, now it crash on an big Mixing issue

**Comment by suerion** [comment]
Here the Log without Realms Fix

https://mclo.gs/dCA5FU1

**Comment by BluCobalt** [comment]
[realmsfix-2.0.7.jar.zip](https://github.com/user-attachments/files/18103178/realmsfix-2.0.7.jar.zip)
Thank you for your bug report. Does this fix it? (remove the .zip)

**Comment by suerion** [comment]
HEy, i will look on it tomorow

**Comment by suerion** [comment]
@BluCobalt is fixed with this version ;)
